r"""languages.py -- the ten visual languages, AS IMPLEMENTED.

DO NOT EDIT BY HAND.  This file is generated from the reference implementation
by `prototypes/export_to_skill.py` in the taskboard repo:

    cd C:\Users\jjgh8\Github\taskboard\.claude\worktrees\kanban-variants
    $env:PYTHONIOENCODING = "utf-8"
    python prototypes\export_to_skill.py

WHY IT IS GENERATED.  The previous hand-written version drifted from the code
without anyone noticing: it listed eight languages where the app rendered ten,
it had never heard of Solari or Blueprint, it kept offering phosphor and bbs as
implemented after they were retired, and its structural tokens were read by no
renderer at all -- the exact "a language definition is code, not a manifest"
failure LANGUAGES.md warns about, committed by the file the doc points at.

WHAT EACH NAME MEANS

    LANGUAGES  every token, as `themes.py` holds it.  Structural tokens
               (`layout`, `hero`, `frame`, `meter`, `base`, `sel`, `tempo`...)
               are READ BY RENDERERS in the reference app -- mutate one and the
               render changes, which is the property that keeps a token from
               being dead metadata.  `prototypes/verify_language.py` asserts it.
    FAMILY     the board layout family: columns | sections | split.
    DOC        each language's doctrine, taken from its Kit class docstring, so
               the prose here cannot drift from the class it describes.
    ORDER      the ten in the order the app's `t` key cycles them.
    RETIRED    two languages the operator removed from the reference app.  They
               remain legitimate choices -- see LANGUAGES.md -- but no kit here
               renders them, and pretending otherwise is what this entry exists
               to prevent.

USING IT

    from languages import LANGUAGES, DOC, FAMILY, ORDER
    tok = LANGUAGES["solari"]        # every token, including the structural ones
    print(DOC["solari"])             # why it commits to what it commits to

Reference frames for all ten live in `assets/languages/` -- board and component
sheet each, one sweep, one fixture, one viewport.  A page that puts the frames,
the tokens and the doctrine side by side is generated by
`prototypes/build_languages_html.py`.

Generated 2026-08-02 from 11 kits in `taskboard/language.py`.
"""
from __future__ import annotations

LANGUAGES: dict[str, dict] = {
    # Naught -- round-dot lattice · mono · red only for alarm
    'naught': dict(
        layout='lattice', hero='naught7', frame='none', meter='dotgrid',
        base='block2', sel='outer', tempo=120, easing='linear',
        ground='#000000', ink='#f5f5f5', mut='#8a8a8a', dim='#242424',
        accent='#d71921', warn='#d71921', alert='#d71921', panel='#0a0a0a',
        focus='#141414',
        calm='#f5f5f5', dot_w=1, gap=0, label='Naught',
        note='round-dot lattice · mono · red only for alarm',
        surface='lattice',
    ),
    # Corgi Engineering -- numbered params · 7-seg display · safety orange
    'corgi': dict(
        layout='strip', hero='corgi', frame='grid', meter='lcd',
        base='segment', numbered=True, sel='solid', tempo=80,
        easing='linear',
        ground='#0d0d0d', ink='#f2f2f2', mut='#9a9a9a', dim='#3a3a3a',
        accent='#ff6600', warn='#ffb000', alert='#d92b1a', panel='#1c1c1c',
        focus='#2a2a2a', screen='#6fe36f', alu='#9a9a9a',
        label='Corgi Engineering',
        note='numbered params · 7-seg display · safety orange',
        surface='display',
    ),
    # Instrument -- round-dot scope · braille numerals · clinical
    'instrument': dict(
        layout='trace', hero='dot', frame='none', meter='braille',
        base='braille', sel='outer', tempo=160, easing='out_cubic',
        ground='#0a0d12', ink='#e8edf2', mut='#6b7785', dim='#333c47',
        accent='#2dd4bf', warn='#fbbf24', alert='#f43f5e', panel='#0e131a',
        focus='#16202b',
        label='Instrument',
        note='round-dot scope · braille numerals · clinical',
        surface='lattice', tick='#333c47', unit='#6b7785',
    ),
    # Swiss -- airy · plain type · one rule · structure by alignment
    'swiss': dict(
        layout='editorial', hero='plain', frame='rule', meter='hairline',
        base='ascii', sel='solid', tempo=240, easing='in_out_cubic',
        ground='#101010', ink='#f4f4f4', mut='#8a8a8a', dim='#3d3d3d',
        accent='#e2231a', warn='#e2231a', alert='#e2231a', panel='#171717',
        focus='#1f1f1f',
        airy=True, columns=3, label='Swiss',
        note='airy · plain type · one rule · structure by alignment',
        pitch=2, surface='figure',
    ),
    # Industrial -- 5 flat colours on grey · colour codes function
    'industrial': dict(
        layout='panel', hero='plain', frame='single', meter='boxed',
        base='block', numbered=True, sel='solid', tempo=60, easing='linear',
        ground='#1a1a1a', ink='#f2f2f2', mut='#8f8f8f', dim='#4a4a4a',
        accent='#ff4b1f', warn='#ffd400', alert='#ff4b1f', panel='#232323',
        focus='#2e2e2e',
        label='Industrial',
        note='5 flat colours on grey · colour codes function',
        plate='#2e2e2e', surface='display',
    ),
    # Nord (base16) -- full scheme · inherits the terminal's world
    'nord': dict(
        layout='split', hero='dot', frame='rule', meter='blocks',
        base='quadrant', sel='round', tempo=140, easing='out_cubic',
        ground='#2e3440', ink='#eceff4', mut='#7b88a1', dim='#4c566a',
        accent='#88c0d0', warn='#ebcb8b', alert='#bf616a', panel='#3b4252',
        focus='#434c5e',
        label='Nord (base16)',
        note="full scheme · inherits the terminal's world",
        surface='untinted',
    ),
    # Darkside -- achromatic · accent = interaction only · moon doodle
    'darkside': dict(
        layout='rail', hero='plain', frame='none', meter='step',
        base='ascii', sel='solid', tempo=300, easing='in_out_cubic',
        ground='#000000', ink='#f5f5f5', mut='#737373', dim='#262626',
        accent='#1783ff', warn='#ffd230', alert='#ff4f42', panel='#121212',
        focus='#1f1f1f',
        calm='#f5f5f5', label='Darkside',
        note='achromatic · accent = interaction only · moon doodle',
        rail='#262626', surface='depth', wordmark='#3a3a3a',
    ),
    # Prism -- two colour systems, one written border · carved ember
    'prism': dict(
        layout='rail', hero='ember', frame='none', meter='ember',
        base='braille', sel='solid', tempo=300, easing='in_out_cubic',
        ground='#0d1117', ink='#e6edf3', mut='#8b98a5', dim='#5b6675',
        accent='#2dd4bf', warn='#fbbf24', alert='#f43f5e', panel='#161b22',
        focus='#1f2630',
        ash='#6b4a3f', bright='#e6edf7', done='#3f9c6d',
        ident='#a3e635 #4ade80 #38bdf8 #60a5fa #a78bfa #22d3ee #fb7185 #fb923c #fbbf24 #818cf8 #e879f9 #f472b6',
        label='Prism', later='#64748b',
        note='two colour systems, one written border · carved ember',
        surface='depth',
    ),
    # Ledger -- paper ground · dot leaders · red = overdue only
    'ledger': dict(
        layout='ruled', hero='dot', frame='ruled', meter='tally',
        base='slab', numbered=True, sel='none', tempo=200, easing='linear',
        ground='#e9e1cf', ink='#1c1a15', mut='#6b6558', dim='#c4b99f',
        accent='#2b3a67', warn='#a8261f', alert='#a8261f', panel='#f2ecdd',
        focus='#ded4bc',
        band='#e0d7c2', calm='#1c1a15', label='Ledger',
        note='paper ground · dot leaders · red = overdue only', pitch=1,
        rule='#8a8272', surface='refuse', tally='▪',
    ),
    # Solari -- flap cells · reverse bands · digits, never bars
    'solari': dict(
        layout='schedule', hero='dot', frame='flaps', meter='odometer',
        base='flap', numbered=False, sel='none', tempo=40, easing='linear',
        ground='#0b0b0c', ink='#f0ede4', mut='#6e6a60', dim='#1f1f22',
        accent='#f5a300', warn='#f5a300', alert='#e03a2f', panel='#17171a',
        focus='#f5a300',
        band='reverse', calm='#f0ede4', flap='#17171a', label='Solari',
        note='flap cells · reverse bands · digits, never bars', pitch=1,
        seam='#1f1f22', surface='refuse',
    ),
    # Blueprint -- cyanotype · dimension spans · knockout emphasis
    'blueprint': dict(
        layout='field', hero='dot', frame='titleblock', meter='dimension',
        base='stencil', numbered=False, sel='none', tempo=180,
        easing='out_cubic',
        ground='#123a5c', ink='#eef4f8', mut='#7fa8c4', dim='#24486b',
        accent='#eef4f8', warn='#7fa8c4', alert='#ff7a5c', panel='#0e2f4a',
        focus='#1a4a72',
        calm='#eef4f8', hatch='╱', knockout=True, label='Blueprint',
        note='cyanotype · dimension spans · knockout emphasis', pitch=1,
        surface='tint',
    ),
}

# board layout family, from Kit.board_layout()
FAMILY: dict[str, str] = {
    'naught': 'columns',
    'corgi': 'sections',
    'instrument': 'columns',
    'swiss': 'sections',
    'industrial': 'columns',
    'nord': 'split',
    'darkside': 'sections',
    'prism': 'sections',
    'ledger': 'sections',
    'solari': 'sections',
    'blueprint': 'sections',
}

# The doctrine, straight off each Kit class -- edit it THERE.
DOC: dict[str, str] = {
    'naught': '''Everything on one visible dot lattice; quantity is discrete lit dots,
never a filled bar; the count is a DRAWN 3x5 sprite; no frames at all.''',
    'corgi': '''Teenage-Engineering grammar: hairline aluminium rules with square
junctions, numbered functional params, all-caps letterspaced labels,
quantity as LCD SEGMENT BARS (the mark is a bar, not a dot).

The board is ONE FULL-WIDTH MODE SURFACE (`layout="strip"`): a numbered
MODE STRIP names every mode and lights the one on screen, and under it the
board mode is a single spec sheet — full-width numbered param rows whose
values stand in engraved slots that align down the whole page. Under any
other `layout` the previous 3-column composition comes back byte for byte
(`_flow_*`).''',
    'instrument': '''Round-dot scope: braille sub-cell dots carry quantity at 2x4 the cell
resolution; the unlit lattice stays faintly visible; no frames.

The board is the SCOPE SCREEN (`layout="trace"`): every phase head carries
a labelled DAY RETICLE, and every task hangs a braille trace sample off it
— same origin, same cells, one cell per day. Under any other `layout` the
previous bench-readout composition comes back byte-for-byte.''',
    'swiss': '''Structure by alignment and emptiness. ONE hairline rule. No boxes, no
markers, no drawn type — counts are typographic, space is the divider.

The board is an EDITORIAL SPREAD (`layout="editorial"`): every entry is
set on a type GRID of `columns` columns — subject · byline · figure — and
the single hairline is the masthead rule under the LEADING phase, not one
rule per head. Under any other `layout` the previous full-width flow rows
come back, byte for byte (`_flow_*`).''',
    'industrial': '''Flat functional colour on grey; everything is labelled and bracketed;
numbered because modes have numbers. Structure is the FUNCTION PLATE
(`layout="panel"`): the head rule is gone, a phase is a plate legend, and
every task is a solid plate-toned block stamped with its two-digit code.
Under any other `layout` the previous boxed composition comes back.''',
    'nord': '''The terminal's own conventional idiom (base16 doctrine) — everything
nord renders is inherited from `Kit`, which was WRITTEN as nord, and that
stays true. This subclass exists for exactly one commitment: the board is
a MASTER/DETAIL SPLIT (`layout="split"`).

Why the split, measured rather than asserted: colour-stripped at 118x30
nord had NO first fixation. Ranked by ink cells and by the weighted
channel sum 0.2126R+0.7152G+0.0722B, the brightest ink on screen belonged
to TEN repeated card titles (238.7, 200 cells) and the only isolated
element — the hero numeral — came FIFTH (117.7, 25 cells) behind the load
plot standing beside it in the same panel (181.2, 61 cells). Nothing won
area AND brightness AND isolation, which is HIERARCHY.md's self-check.

The split gives the eye one subject. HIERARCHY.md's sidebar+detail
pattern is quoted here because its wording is load-bearing: "a narrow
list (25-30 %) driving a wide detail pane. THE LIST KEEPS SELECTION
STATE; the detail pane is the only thing that changes." Selection is
constitutive of the pattern, so the detail follows the real cursor
(`KanbanBoard.on_card_focused`) — a static default would have been an
imitation of the pattern, not the pattern.

Under any other `layout` every method below falls through to `super()`,
i.e. the base kit, and nord renders byte-for-byte as it always did.''',
    'darkside': '''Moonshot's language (ported from the Kimi fork, then held to this
repo's laws): achromatic greys; the ONE accent (KMBlue) is spent
EXCLUSIVELY on interactive affordances — the knob, the switch state, the
active tab. Passive data is grey STEPS whose levels ride on SHAPE (the
fork's grey-on-grey meter died in greyscale — fixed here). Depth is a
background grey-step, never a border. Lowercase register; identity is a
date-driven moon doodle on a deliberately recessive wordmark.''',
    'prism': '''Darkside's descendant, and the only language here that was carried by a
whole app until it had opinions before it was ever written down.

IT IS NOT DARKSIDE RECOLOURED, and the difference is a mechanism. Darkside
spends its one accent on interactivity and keeps every other mark grey.
Prism spends colour TWICE, on two systems, with a BORDER BETWEEN THEM that
is written down and measured:

  * IDENTITY hues NAME -- which project a mark belongs to (twelve of them);
  * SEVERITY hues JUDGE -- `alert` is overdue, `warn` is due today;
  * the accent CALLS ATTENTION -- today's rule, focus, keys.

No mark may wear two of those jobs. On main that border is a test, not a
convention: `tests/test_palette_ration.py` computes euclidean rgb distance
across the whole palette, so re-adding a colliding hue turns it red
whatever it is called. It exists because `amber` was once a project colour
AND the due-today colour AT THE SAME HEX -- one mark meaning two things in
five views. Priority is a GLYPH here (`!2`) rather than a hue precisely
because its orange collided with a project's at nine rgb units.

The second commitment is the EMBER: quantity is a solid field being
consumed, not a track being filled, with the frontier at half-cell
precision (`meter="ember"`, and the hero carves its numeral out of the same
field). Each cell is field or figure and never both, so the
two-colours-per-cell law is satisfied BY COMPOSITION instead of policed
afterwards.''',
    'ledger': '''Double-entry bookkeeping — and the ONLY language printed on a LIGHT
ground, which is what makes it unmistakable once colour is stripped away:
seven languages glow, this one is read.

Commitments:

* structure is RULED MONEY COLUMNS, never boxes. Every rule position is
  computed in ONE place (`cols()`), which both the renderer and the
  acceptance check read — so "the rules and the content share the same
  cells" is true by construction and provable by assertion;
* every gap between a name and its figure closes with DOT LEADERS. On a
  ledger page space is either earned or filled, because an open gap is
  where a figure could be forged;
* quantity is TALLY marks in groups of five (`meter="tally"`) — the
  mechanism used when you COUNT rather than measure;
* every 5th line of the page carries the band tint, the way ruled paper
  is printed: the aid that lets an eye cross 80 cells without losing its
  row;
* selection is a MARGIN mechanism — the row's tint plus its weight, never
  a border (`sel="none"` spends no border at all, so the page keeps its
  one strongest divider unspent);
* the RED PEN is literal debt: the alert hue appears on OVERDUE entries
  and nowhere else. A page with nothing owed is ink on paper.''',
    'solari': '''THE SPLIT-FLAP DEPARTURE BOARD. The product becomes ONE SCHEDULE: a
task is a ROW, a phase is a GATE, and the task's state is a WORD in a
status column.

Commitments, each of which is a mechanism below and not a note:

* **quantity is DIGITS in flap cells, never a bar** (`meter="odometer"`).
  No other language in the set states a figure where the others draw a
  length, and it is the reason a departure board is legible at fifty
  metres: you read `07`, you do not estimate a bar. DATAVIZ.md law 1 is
  satisfied by construction — a 3 and a 7 differ in SHAPE with every
  colour stripped away;
* **the SEAM is the whole divider vocabulary.** `frame="flaps"` says the
  structure device is the cell FACE a character is flipped onto, so this
  language spends no rule at all: `rule_line()` returns None and every
  schedule row closes with one `▁` in the `seam` tone;
* **headers are BANDS in reverse video** (`band="reverse"`), EXACTLY as
  wide as the seams under them. Band and seam are both cut from one
  geometry seat (`fields()`), so "the band matches the seam grid" is true
  by construction rather than by inspection;
* **TABULAR fields, padded to their widest content.** Every column is a
  fixed width and every figure is zero-padded, so nothing on the page
  moves sideways when a value changes (Bodmer T1/T2 — the anti-jiggle
  law, and the reason a flap board can be read while it is flipping);
* **amber is RATIONED to selection and to values in flight** (a task
  inside its boarding window). A calm page carries none. Red is narrower
  still: it appears on LATE and nowhere else.

The ITEM field is deliberately the ONE field with no colour tag on it: it
inherits the widget's colour, which is what lets the selection band invert
it (`.kb-card:focus` sets ground-on-amber) instead of printing cream on
amber at 1.8:1.''',
    'blueprint': '''THE CYANOTYPE TECHNICAL DRAWING. The frame stops CONTAINING and starts
MEASURING: not one element on this sheet is boxed, and every quantity is a
DIMENSION SPAN with its figure standing on the span itself.

Commitments, each of which is a mechanism below and not a note:

* **quantity is a DIMENSION SPAN** (`meter="dimension"`). `├──── 03D ────┤`
  — the run measures and the figure states, so the reading never depends on
  estimating a length. The scale is a CONSTANT (`SCALE_DAYS` for a due
  span, `SCALE_COUNT` for a head's load), which is what makes DATAVIZ.md
  law 2 true by construction: a kit method sees one row at a time and can
  never be handed its siblings' maximum, so a shared ceiling has to be
  declared rather than derived. Two spans anywhere on the sheet are
  comparable because neither was normalized to itself;
* **NOTHING IS BOXED, at any width.** `layout="field"` lays items on an
  open field and hangs their metadata off an EXTENSION LEADER
  (`·── PROJ ── BACKLOG ── HIGH`). The only box-drawing glyphs this
  language draws are `─ ━ ├ ┤ ╌` (the dimension vocabulary), `┌ ┐ └ ┘`
  (registration marks) and the hatch — TEN, and not one of them is a
  vertical stroke or a rectangle junction, so a containing box here is not
  merely absent: it is unconstructable. (A terminator may stand alone in a
  two-cell seat — the calendar day — where a span does not fit. That is a
  renunciation, and it is the only place it happens.);
* **a SERIES is an ORDINATE DIMENSION STACK** (`series()`). A conventional
  chart axis is `│` and `└` and is therefore unconstructable here, but an
  axis is not the only way to draw a trace: a drawing office schedules
  ordinate dimensions from a common datum, and this does the same — every
  sample a run from the sheet's left terminator, its figure standing on
  the run, and **the locus of the closing terminators IS the curve**. The
  vertical a plot appears to need is never drawn; it is the column the
  terminators fall in. The scale is PUBLISHED on the last row as a
  full-width span figured with the ceiling, which is what lets the ceiling
  be derived from the series without breaking DATAVIZ law 2 (found by the
  first app to carry this language, and decided rather than renounced —
  `tui-demos` LIMITS L-34);
* **the whole frame budget is ONE TITLE BLOCK** (`frame="titleblock"`), a
  3-row stamp docked to the bottom corner carrying the sheet's identity,
  its revision date, its work tally and its state. Its two rules are the
  only strokes on the page, and `stamp()` builds it from ROWS OF CELLS so
  that an app with no mode strip can still have one (L-32);
* **emphasis is KNOCKOUT** (`knockout=True`): exactly ONE element per view
  reverses to a pale ground with dark ink, and it is the title block's
  STATE cell. That is the first-fixation law here, and it is why chroma
  stays near zero — `ink`, `mut` and `dim` are one cyan family and the
  silhouette is carried by spans, leaders and the block;
* **held work is HATCHED, never coloured** (`hatch="╱"`), so blocked reads
  with the colour stripped away and costs none of the rationed chroma;
* **alert is spent on OVERDUE and nothing else.** A calm sheet carries zero
  `alert`.

**The knockout is the title block's cell rather than the most overdue ITEM,
and that is a deviation with a mechanical reason.** A kit method is handed
one card at a time and has no cross-card knowledge, so "the single most
urgent item" cannot be identified without ranking the cards in `kanban.py`
(the shape of nord's selection problem). The one seat that DOES see the
whole board is `Kit.mood`, which the app computes from the real task list,
and the title block is where it lands. A per-item knockout is the named
follow-up.''',
}

ORDER: list[str] = ['naught', 'corgi', 'instrument', 'swiss', 'industrial', 'nord', 'darkside', 'prism', 'ledger', 'solari', 'blueprint']

# Retired from the reference app -- still valid to CHOOSE.
RETIRED: dict[str, tuple[str, str]] = {
    'phosphor': (
        'one hue at many lightnesses (amber/green CRT); severity must ride brightness and glyph, never a second hue',
        'retired from the reference app 2026-07-26 by operator curation -- still a valid language to choose'),
    'bbs': (
        'full 16 colours, solid ink, double-line box drawing, block-gradient shading (ANSI/BBS art)',
        'retired from the reference app 2026-07-26 by operator curation -- still a valid language to choose'),
}
