"""`L` links (batch 2026-10-04-batch-01, HLR-502: LLR-502.1, LLR-502.2, LLR-502.4).

Field report: the only way to link was `b` → an unordered list of every open task of
every project, no search, nothing saying what a link would mean (DEPS-CONTRACT.md).
The operator's verdict (round 3, D-B2): one key, `L`, a picker with the same project
first and by due, type to filter, done work excluded, loop candidates dimmed with the
path, an already-linked row that removes, and a hint per row on what the link means.

Law: a link is added only when it is not the task itself, not closed and closes no
loop; adding and removing are one undo step each. Synthetic boards only.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pytest
from rich.text import Text

import kg_board
from taskboard.app import TaskboardApp
from taskboard.keymap import KEYMAP, key_bar_plain
from taskboard.modals import LinkPicker
from taskboard.models import link_candidates, link_refusal

# TC-509's oracle: `evidence/p1-tables.txt` (sha256 0583fb00…), generated by the
# prototype's rule functions at P1 — (same project?, task id, hint) in order, per waiter;
# precondition: tw6 waits on tw5. Pasted, never re-derived from the code under test.
TC_509 = {
    'tw5': [
        (True, 'tw2', '✓ linked (↵ removes) · ok — due 7d before this starts'),
        (True, 'tw3', 'ok — due 6d before this starts'),
        (True, 'tw4', '✓ linked (↵ removes) · ◂ overlaps 3d: due Oct 6, this starts Oct 4'),
        (True, 'tw6', '⟲ would loop: this → SEO redirects map → this'),
        (False, 'ta1', 'ok — due 9d before this starts'),
        (False, 'to1', 'ok — due 5d before this starts'),
        (False, 'ta6', 'ok — due 5d before this starts'),
        (False, 'to3', 'ok — due 4d before this starts'),
        (False, 'tm6', 'ok — due 3d before this starts'),
        (False, 'tm2', 'ok — due 2d before this starts'),
        (False, 'ta3', 'ok — due 1d before this starts'),
        (False, 'to2', 'ok — due 1d before this starts'),
        (False, 'ta4', '◂ overlaps 1d: due Oct 4, this starts Oct 4'),
        (False, 'ta2', '◂ overlaps 4d: due Oct 7, this starts Oct 4'),
        (False, 'td2', '◂ overlaps 6d: due Oct 9, this starts Oct 4'),
        (False, 'tm3', '◂ overlaps 9d: due Oct 12, this starts Oct 4'),
        (False, 'td4', '◂ overlaps 15d: due Oct 18, this starts Oct 4'),
        (False, 'to5', '◂ overlaps 17d: due Oct 20, this starts Oct 4'),
        (False, 'tm4', '◂ overlaps 25d: due Oct 28, this starts Oct 4'),
        (False, 'td3', '◂ overlaps 27d: due Oct 30, this starts Oct 4'),
        (False, 'tm5', '◂ overlaps 32d: due Nov 4, this starts Oct 4'),
        (False, 'td5', '◂ overlaps 57d: due Nov 29, this starts Oct 4'),
        (False, 'ta5', "no due date — timing can't be checked"),
        (False, 'to4', "no due date — timing can't be checked"),
    ],
    'ta2': [
        (True, 'ta1', 'ok — due on or before the day this is due'),
        (True, 'ta6', 'ok — due on or before the day this is due'),
        (True, 'ta3', '✓ linked (↵ removes) · ok — due on or before the day this is due'),
        (True, 'ta4', 'ok — due on or before the day this is due'),
        (True, 'ta5', "no due date — timing can't be checked"),
        (False, 'tw2', 'ok — due on or before the day this is due'),
        (False, 'tw3', 'ok — due on or before the day this is due'),
        (False, 'to1', 'ok — due on or before the day this is due'),
        (False, 'to3', 'ok — due on or before the day this is due'),
        (False, 'tm6', 'ok — due on or before the day this is due'),
        (False, 'tm2', 'ok — due on or before the day this is due'),
        (False, 'to2', 'ok — due on or before the day this is due'),
        (False, 'tw4', 'ok — due on or before the day this is due'),
        (False, 'td2', '◂ overlaps 2d: due Oct 9, this is due Oct 7'),
        (False, 'tw5', '◂ overlaps 3d: due Oct 10, this is due Oct 7'),
        (False, 'tm3', '◂ overlaps 5d: due Oct 12, this is due Oct 7'),
        (False, 'tw6', '◂ overlaps 7d: due Oct 14, this is due Oct 7'),
        (False, 'td4', '◂ overlaps 11d: due Oct 18, this is due Oct 7'),
        (False, 'to5', '◂ overlaps 13d: due Oct 20, this is due Oct 7'),
        (False, 'tm4', '◂ overlaps 21d: due Oct 28, this is due Oct 7'),
        (False, 'td3', '◂ overlaps 23d: due Oct 30, this is due Oct 7'),
        (False, 'tm5', '◂ overlaps 28d: due Nov 4, this is due Oct 7'),
        (False, 'td5', '◂ overlaps 53d: due Nov 29, this is due Oct 7'),
        (False, 'to4', "no due date — timing can't be checked"),
    ],
    'to4': [
        (True, 'to1', "this has no dates — timing can't be checked"),
        (True, 'to3', "this has no dates — timing can't be checked"),
        (True, 'to2', "this has no dates — timing can't be checked"),
        (True, 'to5', "this has no dates — timing can't be checked"),
        (False, 'ta1', "this has no dates — timing can't be checked"),
        (False, 'tw2', "this has no dates — timing can't be checked"),
        (False, 'tw3', "this has no dates — timing can't be checked"),
        (False, 'ta6', "this has no dates — timing can't be checked"),
        (False, 'tm6', "this has no dates — timing can't be checked"),
        (False, 'tm2', "this has no dates — timing can't be checked"),
        (False, 'ta3', "this has no dates — timing can't be checked"),
        (False, 'ta4', "this has no dates — timing can't be checked"),
        (False, 'tw4', "this has no dates — timing can't be checked"),
        (False, 'ta2', "this has no dates — timing can't be checked"),
        (False, 'td2', "this has no dates — timing can't be checked"),
        (False, 'tw5', "this has no dates — timing can't be checked"),
        (False, 'tm3', "this has no dates — timing can't be checked"),
        (False, 'tw6', "this has no dates — timing can't be checked"),
        (False, 'td4', "this has no dates — timing can't be checked"),
        (False, 'tm4', "this has no dates — timing can't be checked"),
        (False, 'td3', "this has no dates — timing can't be checked"),
        (False, 'tm5', "this has no dates — timing can't be checked"),
        (False, 'td5', "this has no dates — timing can't be checked"),
        (False, 'ta5', "this has no dates — timing can't be checked"),
    ],
}


def _toasts(app) -> list[str]:
    return [str(t.render()) for t in app.screen.query("Toast")]


def _plains(ol) -> list[str]:
    return [ol.get_option_at_index(i).prompt.plain for i in range(ol.option_count)]


@pytest.mark.parametrize("waiter", ["tw5", "ta2", "to4"])
def test_TC_509_candidates_and_hints_equal_the_oracle(waiter):
    """TC-509 (LLR-502.2): over the kg board with `tw6` waiting on `tw5`, the
    candidates for waiters `tw5`, `ta2` (no start) and `to4` (no dates) — order,
    section, loop and hint — equal the P1 oracle row by row; the forms reached are
    derived from the oracle and guarded == 7 (six timing forms + the loop). RED: a
    done task listed, an unsorted list, a hint off by a day."""
    b = kg_board.build()
    b.task_by_id("tw6").depends_on.append("tw5")
    got = []
    for c in link_candidates(b, b.task_by_id(waiter)):
        if c.loop:
            hint = "⟲ would loop: this → " + " → ".join(t.title for t in c.loop[1:-1]) + " → this"
        else:
            hint = ("✓ linked (↵ removes) · " if c.linked else "") + c.hint
        got.append((c.same_project, c.task.id, hint))
    assert got == TC_509[waiter]
    forms = {re.sub(r"\d+d|[A-Z][a-z]{2} \d+", "#", h.split(" · ")[-1])
             for rows in TC_509.values() for _s, _i, h in rows}
    forms = {f if not f.startswith("⟲") else "⟲" for f in forms}
    assert len(forms) == 7, forms


def test_TC_507_a_link_is_refused_when_it_is_self_closed_or_a_loop():
    """TC-507 (LLR-502.1): the task itself, a closed task and a loop are refused,
    the loop named by its path and shortened in the middle past six names. RED: a
    link written before the check."""
    b = kg_board.build()
    m2 = b.task_by_id("tm2")
    assert link_refusal(b, m2, m2) == "a task cannot wait on itself"
    assert link_refusal(b, m2, b.task_by_id("tw1")) == "Design homepage mockups is closed"
    assert link_refusal(b, m2, b.task_by_id("tm5")) == (
        "would create a loop: Audit dependencies → Beta release to testers → Offline sync "
        "→ Add push notifications → Audit dependencies")
    assert link_refusal(b, m2, b.task_by_id("to4")) is None
    from taskboard.models import Task
    chain = [Task(f"T{i}", phase="Doing", depends_on=[f"T{i - 1}"] if i else [], id=f"T{i}")
             for i in range(9)]
    b.tasks += chain
    long = link_refusal(b, chain[0], chain[8])
    assert long.startswith("would create a loop: T0 → T8 → T7 → … → ") and long.count("→") == 5


def test_TC_508_L_is_one_new_key_painted_at_80_columns():
    """TC-508 (LLR-502.1, ux UX-3): `L` → `link` is the keymap's only new row, in
    the primary layer of group `task`, scoped to the five views with a selection;
    it is painted in the primary key bar at 80 columns in kanban and gantt with no
    key counted as dropped; `BlockerPicker` is gone from the package. RED on base:
    `L` unbound (P-13)."""
    rows = [k for k in KEYMAP if k.keys == "L"]
    assert len(rows) == 1 and rows[0].action == "link" and rows[0].primary
    assert rows[0].group == "task"
    assert set(rows[0].views) == {"swimlanes", "agenda", "gantt", "kanban", "focus"}
    for view in ("kanban", "gantt"):
        bar = key_bar_plain(80, view, "primary")
        assert " L" in bar and not re.search(r"\+\d+$", bar), bar
    pkg = Path(__file__).resolve().parents[1] / "taskboard"
    assert not any("BlockerPicker" in p.read_text(encoding="utf-8") for p in pkg.glob("*.py"))


async def test_TC_510_the_picker_filters_starts_on_a_candidate_and_creates(tmp_path):
    """TC-510 (LLR-502.2, ux UX-10, qa Q-14): the title names the waiter, the count
    reads "24 of 24 open", the highlight starts on the first candidate (not on the
    create row); typing `ma` leaves 4 of 24 and the create row echoes it; a filter
    matching nothing leaves the create row alone; the loop row is disabled. RED: a
    highlight on create (↵ would make a junk task)."""
    path = tmp_path / "board.json"
    b = kg_board.shifted(path)
    b.task_by_id("tw6").depends_on.append("tw5")
    b.save()
    app = TaskboardApp(board_path=str(path))
    async with app.run_test(size=(118, 40)) as pilot:
        await pilot.press("4")
        app.selected_task_id = "tw5"
        await pilot.press("L")
        await pilot.pause()
        scr = app.screen
        assert isinstance(scr, LinkPicker)
        ol = scr.query_one("#link-list")
        assert str(scr.query_one("#link-count").render()) == "24 of 24 open"
        assert ol.get_option_at_index(ol.highlighted).id == "c:tw2"
        loop = next(i for i in range(ol.option_count) if ol.get_option_at_index(i).id == "c:tw6")
        assert ol.get_option_at_index(loop).disabled
        assert "⟲ would loop: this → SEO redirects map → this" in _plains(ol)[loop]
        await pilot.press("m", "a")
        await pilot.pause()
        assert str(scr.query_one("#link-count").render()) == "4 of 24 open"
        assert _plains(ol)[0] == "+ create “ma” as a new task it waits on"
        await pilot.press("z", "z", "z")
        await pilot.pause()
        assert ol.option_count == 1


async def test_AT_502_L_links_from_the_picker(tmp_path):
    """AT-502 (US-502): on the shifted kg board, kanban, `L` on `Launch new homepage`
    opens "Launch new homepage waits on…"; with `SEO redirects map` waiting on it,
    that row is disabled with its loop; typing `crash` and ↵ links `Crash reporting`
    — the card gains `◂3`, the saved file holds the id; `L` again, typing `crash`,
    ↵ removes it; `u` restores it; the create row with a typed title makes a task in
    the waiter's project, first phase, no dates, and links it; with an empty filter
    it asks for the title; titles holding markup are painted literally. RED on base:
    `L` unbound (P-13)."""
    path = tmp_path / "board.json"
    b = kg_board.shifted(path)
    b.task_by_id("tw6").depends_on.append("tw5")
    b.task_by_id("tm6").title = "Crash [b]reporting[/b]"
    b.save()
    app = TaskboardApp(board_path=str(path))
    async with app.run_test(size=(118, 40), notifications=True) as pilot:
        await pilot.press("4")
        await pilot.pause()
        app.selected_task_id = "tw5"
        await pilot.press("L")
        await pilot.pause()
        assert str(app.screen.query_one(".modal-title").render()) == "Launch new homepage waits on…"
        await pilot.press(*"crash")
        await pilot.pause()
        assert any("Crash [b]reporting[/b]" in p for p in _plains(app.screen.query_one("#link-list")))
        await pilot.press("enter")
        await pilot.pause()
        saved = {t["id"]: t for t in json.loads(path.read_text(encoding="utf-8"))["tasks"]}
        assert saved["tw5"]["depends_on"] == ["tw2", "tw4", "tm6"]
        # the card now says it waits on three (code review N1)
        painted = [s.text for s in app.screen._compositor.render_strips(app.screen.size)]
        assert any("◂3" in r for r in painted)
        assert any("Launch new homepage waits on Crash [b]reporting[/b] · u undo" in t
                   for t in _toasts(app))
        await pilot.press("L")
        await pilot.pause()
        await pilot.press(*"crash")
        await pilot.press("enter")
        await pilot.pause()
        assert app.board.task_by_id("tw5").depends_on == ["tw2", "tw4"]
        await pilot.press("u")
        await pilot.pause()
        assert app.board.task_by_id("tw5").depends_on == ["tw2", "tw4", "tm6"]
        n = len(app.board.tasks)
        await pilot.press("L")
        await pilot.pause()
        await pilot.press(*"Hero copy")
        await pilot.press("up")
        await pilot.press("enter")
        await pilot.pause()
        assert len(app.board.tasks) == n + 1
        new = app.board.tasks[-1]
        assert (new.title, new.project_id, new.phase, new.start_date, new.due_date) == (
            "Hero copy", "pweb", "Backlog", None, None)
        assert app.board.task_by_id("tw5").depends_on[-1] == new.id
        await pilot.press("L")
        await pilot.pause()
        await pilot.press("up", "enter")
        await pilot.pause()
        assert type(app.screen).__name__ == "TextPrompt"
        await pilot.press("escape")
        await pilot.pause()
        app.selected_task_id = "tm2"
        await pilot.press("L")
        await pilot.pause()
        await pilot.press(*"beta")
        await pilot.pause()
        ol = app.screen.query_one("#link-list")
        beta = next(i for i in range(ol.option_count) if ol.get_option_at_index(i).id == "c:tm5")
        assert ol.get_option_at_index(beta).disabled
        assert "⟲ would loop" in _plains(ol)[beta]
        await pilot.press("escape")
        await pilot.pause()
        assert app.board.task_by_id("tm2").depends_on == []


async def test_TC_507_the_app_refuses_a_loop_even_when_asked_directly(tmp_path):
    """TC-507 (LLR-502.1; code review T2, battery P14): the picker never offers a
    loop, so the app's own refusal is the last guard — `link_tasks(tm2, tm5)`
    leaves `depends_on` and the undo stack as they were and names the loop. RED:
    the link written before the refusal check."""
    path = tmp_path / "board.json"
    kg_board.shifted(path)
    app = TaskboardApp(board_path=str(path))
    async with app.run_test(size=(118, 40), notifications=True) as pilot:
        await pilot.pause()
        stack = len(app._undo_stack)
        m2, m5 = app.board.task_by_id("tm2"), app.board.task_by_id("tm5")
        assert app.link_tasks(m2, m5) is False
        await pilot.pause()
        assert m2.depends_on == [] and len(app._undo_stack) == stack
        assert any("would create a loop: Audit dependencies → Beta release to testers" in t
                   for t in _toasts(app))


async def test_TC_510_rows_paint_their_state_and_undo_takes_a_link_back(tmp_path):
    """TC-510 (LLR-502.2, code review T5/T6): the picker's painted row for a linked
    task reads "✓ linked (↵ removes) · …"; link then `u` takes the link back; the
    create row then `u` takes the link back and the created task stays. RED: a
    linked row painted without its state; a link that `u` cannot take back."""
    path = tmp_path / "board.json"
    kg_board.shifted(path)
    app = TaskboardApp(board_path=str(path))
    async with app.run_test(size=(118, 40), notifications=True) as pilot:
        await pilot.press("4")
        await pilot.pause()
        app.selected_task_id = "tw5"
        await pilot.press("L")
        await pilot.pause()
        rows = _plains(app.screen.query_one("#link-list"))
        tw4 = next(r for r in rows if r.lstrip().startswith("Optimize image assets"))
        assert "✓ linked (↵ removes) · ◂ overlaps 3d" in tw4
        await pilot.press(*"rotate", "enter")
        await pilot.pause()
        assert app.board.task_by_id("tw5").depends_on[-1] == "to2"
        await pilot.press("u")
        await pilot.pause()
        assert app.board.task_by_id("tw5").depends_on == ["tw2", "tw4"]
        n = len(app.board.tasks)
        await pilot.press("L")
        await pilot.pause()
        await pilot.press(*"Copy deck", "up", "enter")
        await pilot.pause()
        assert len(app.board.tasks) == n + 1
        await pilot.press("u")
        await pilot.pause()
        assert app.board.task_by_id("tw5").depends_on == ["tw2", "tw4"]
        assert app.board.tasks[-1].title == "Copy deck"
